version = 1
SPDX-PackageName = "Cesium"
SPDX-PackageSupplier = "Cesium contributors <https://github.com/ForNeVeR/Cesium>"
SPDX-PackageDownloadLocation = "https://github.com/ForNeVeR/Cesium"

[[annotations]]
path = ".idea/**/*"
precedence = "override"
SPDX-FileCopyrightText = "2022 Cesium contributors <https://github.com/ForNeVeR/Cesium>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".vscode/**/*"
precedence = "override"
SPDX-FileCopyrightText = "2021 Cesium contributors <https://github.com/ForNeVeR/Cesium>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "**/*.DotSettings"
precedence = "override"
SPDX-FileCopyrightText = "2022 Cesium contributors <https://github.com/ForNeVeR/Cesium>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "Cesium.CodeGen.Tests/verified/*.txt",
    "Cesium.Compiler.Tests/verified/*.txt",
    "Cesium.Parser.Tests/**/verified/*.txt",
    "Cesium.TestFramework.Tests/verified/*.txt",
    "Cesium.IntegrationTests/**/*.in"
]
precedence = "override"
SPDX-FileCopyrightText = "2025 Cesium contributors <https://github.com/ForNeVeR/Cesium>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "Cesium.Templates/**/*"
precedence = "override"
SPDX-FileCopyrightText = "2025 Cesium contributors <https://github.com/ForNeVeR/Cesium>"
SPDX-License-Identifier = "CC0-1.0"
