# SPDX-FileCopyrightText: 2025-2026 Cesium contributors <https://github.com/ForNeVeR/Cesium>
#
# SPDX-License-Identifier: MIT

name: Run Build and Unit tests

on:
  push:
    branches:
    - main
    - renovate/**
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: ${{ matrix.environment.image }}
    name: check.${{ matrix.environment.name }}
    strategy:
      matrix:
        environment:
        - image: macos-15
          name: macos
        - image: ubuntu-24.04
          name: linux
        - image: windows-2025
          name: windows
      fail-fast: false
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - name: 📝 Fetch Sources 📝
        uses: actions/checkout@v6

      - name: 💡 Perform Common Steps 💡
        uses: ./.github/workflows/perform-common-steps

      - name: 🛠 Build Solution 🛠
        shell: bash
        run: dotnet nuke CompileAll

      - name: ✅ Run Unit Tests ✅
        shell: bash
        run: dotnet nuke TestAll

  encoding:
    runs-on: ubuntu-latest
    steps:
      - name: 📝 Fetch Sources 📝
        uses: actions/checkout@v6
      - name: ✅ Verify encoding ✅
        shell: pwsh
        run: scripts/Test-Encoding.ps1

  licenses:
    runs-on: ubuntu-latest
    steps:
      - name: 📝 Fetch Sources 📝
        uses: actions/checkout@v6
      - name: ✅ REUSE license check ✅
        uses: fsfe/reuse-action@v6
