# SPDX-FileCopyrightText: 2025 Cesium contributors <https://github.com/ForNeVeR/Cesium>
#
# SPDX-License-Identifier: MIT

name: Run Build and Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - macos-latest
          - ubuntu-latest
          - windows-latest
      fail-fast: false
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - name: 📝 Fetch Sources 📝
        uses: actions/checkout@v4

      - name: 💡 Perform Common Steps 💡
        uses: ./.github/workflows/perform-common-steps

      - name: 🛠 Build Solution 🛠
        shell: bash
        run: dotnet nuke CompileAll

      - name: 🚚 Pack Compiler Runtime-Specific Bundles 🚚
        shell: bash
        run: dotnet nuke PackAllCompilerRuntimeSpecificBundles

      - name: 📦 Pack Compiler NuPkg 📦
        shell: bash
        run: dotnet nuke PackCompilerNuPkg

      - name: ✅ Run Unit Tests ✅
        shell: bash
        run: dotnet nuke TestAll

  encoding:
    runs-on: ubuntu-latest
    steps:
      - name: 📝 Fetch Sources 📝
        uses: actions/checkout@v4
      - name: ✅ Verify encoding ✅
        shell: pwsh
        run: scripts/Test-Encoding.ps1

  licenses:
    runs-on: ubuntu-latest
    steps:
      - name: 📝 Fetch Sources 📝
        uses: actions/checkout@v4
      - name: ✅ REUSE license check ✅
        uses: fsfe/reuse-action@v5
